# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- dev

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: Restore Nuget Packages
  inputs:
    command: 'restore'
    projects: '**/WebApp.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: Build Web App
  inputs:
    command: 'build'
    projects: '**/WebApp.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Run Unit Tests
  inputs:
    command: 'test'
    projects: '**/*UnitTest*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Create Web App Package (.zip)
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact (WebApp.zip)'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'